//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Validators {
    
    private ValidatorsValidator[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Validator", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ValidatorsValidator[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ValidatorsValidator {
    
    private ValidatorsValidatorProperty[] propertyField;
    
    private string typeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Property", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ValidatorsValidatorProperty[] Property {
        get {
            return this.propertyField;
        }
        set {
            this.propertyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ValidatorsValidatorProperty {
    
    private string nameField;
    
    private bool requiredField;
    
    private bool visibleField;
    
    private string errorMessageField;
    
    private string regularExpressionField;
    
    private string compareField;
    
    private bool dateValidationField;
    
    private bool dateNotInPastValidationField;
    
    private bool dateNotInFutureValidationField;
    
    private bool dateGreaterThanAttributeOrNullValidationField;
    
    private bool timeValidationField;
    
    private bool timeGreaterThanEqualAttributeValidationField;
    
    private bool timeGreaterThanAttributeOrNullValidationField;
    
    public ValidatorsValidatorProperty() {
        this.requiredField = false;
        this.visibleField = true;
        this.dateValidationField = false;
        this.dateNotInPastValidationField = false;
        this.dateNotInFutureValidationField = false;
        this.dateGreaterThanAttributeOrNullValidationField = false;
        this.timeValidationField = false;
        this.timeGreaterThanEqualAttributeValidationField = false;
        this.timeGreaterThanAttributeOrNullValidationField = false;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool Required {
        get {
            return this.requiredField;
        }
        set {
            this.requiredField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(true)]
    public bool Visible {
        get {
            return this.visibleField;
        }
        set {
            this.visibleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ErrorMessage {
        get {
            return this.errorMessageField;
        }
        set {
            this.errorMessageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string RegularExpression {
        get {
            return this.regularExpressionField;
        }
        set {
            this.regularExpressionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Compare {
        get {
            return this.compareField;
        }
        set {
            this.compareField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool DateValidation {
        get {
            return this.dateValidationField;
        }
        set {
            this.dateValidationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool DateNotInPastValidation {
        get {
            return this.dateNotInPastValidationField;
        }
        set {
            this.dateNotInPastValidationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool DateNotInFutureValidation {
        get {
            return this.dateNotInFutureValidationField;
        }
        set {
            this.dateNotInFutureValidationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool DateGreaterThanAttributeOrNullValidation {
        get {
            return this.dateGreaterThanAttributeOrNullValidationField;
        }
        set {
            this.dateGreaterThanAttributeOrNullValidationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool TimeValidation {
        get {
            return this.timeValidationField;
        }
        set {
            this.timeValidationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool TimeGreaterThanEqualAttributeValidation {
        get {
            return this.timeGreaterThanEqualAttributeValidationField;
        }
        set {
            this.timeGreaterThanEqualAttributeValidationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool TimeGreaterThanAttributeOrNullValidation {
        get {
            return this.timeGreaterThanAttributeOrNullValidationField;
        }
        set {
            this.timeGreaterThanAttributeOrNullValidationField = value;
        }
    }
}
